apiVersion: apps/v1
kind: Deployment
metadata:
  name: kodeploy-core
  namespace: default
  labels:
    app: kodeploy-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kodeploy-core
  template:
    metadata:
      labels:
        app: kodeploy-core
    spec:
      serviceAccountName: kodeploy-core
      containers:
        - name: core
          image: ghcr.io/yuntyu01/kodeploy-core:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: kodeploy-core-env
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
      imagePullSecrets:
        - name: ghcr-auth
